### ISSUE TITLE
"Deprecated Attributes - cannot be overridden by user styles" - but yes, they can?!

### ISSUE THREAD

**Issue by jmuheim** [karlgroves/diagnostic.css#18]
I wonder about this line:

https://github.com/karlgroves/diagnostic.css/blob/master/diagnostic.css#L31

I didn't check it myself, but a quick search on the web reveals e.g. this:

[CSS specificity and deprecated HTML attributes](http://stackoverflow.com/questions/10791929/css-specificity-and-deprecated-html-attributes)

There it's stated that these attributes can be overridden by CSS.

Who's right?

**Comment by karlgroves** [comment]
Thanks for bringing this up. I agree that the feedback provided by diagnostics.css is incorrect.  As you note, those attributes can be overridden by CSS.

I still believe it is a worthwhile check, and here's why: 

Some users create custom user stylesheets. If they create custom styles, they might not override things like background colors.  In other words, they'd basically have to create their user stylesheet with a complete reset in order to have the necessary control over stuff like that.

How many users use custom stylesheets? I don't know. While I personally know a small handful, I suspect they represent the severe edge case - especially since the development of so many better tools out there for Low Vision users.  That said, I don't really have hard data to back this up.

I'm definitely open to more conversation and would welcome a PR.

**Comment by jmuheim** [comment]
I totally agree with you. I would simply change the alert to something like this: "Deprecated Attributes - should not be used anymore"
